apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metis-md-collector.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "metis-md-collector.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metis-md-collector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: public.ecr.aws/o2c0x5x8/metis-md-collector:latest
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: {{ .Values.appEnv }}
            - name: API_GATEWAY_HOST
              value: {{ .Values.apiGatewayHost }}
            - name: API_GATEWAY_PATH
              value: {{ .Values.apiGatewayPath }}
            - name: API_GATEWAY_PORT
              value: {{ .Values.apiGatewayPort }}
            - name: WEB_APP_HOST
              value: {{ .Values.webAppHost }}
            - name: WEB_APP_PORT
              value: {{ .Values.webAppPort }}
            - name: API_KEY
              value: {{ .Values.apiKey | required "Api key is required" }}
            - name: DB_CONNECTION_STRINGS
              value: {{ .Values.dbConnectionStrings | required "Connection string is required" }}
            - name: IGNORE_CURRENT_TIME
              value: {{ .Values.ignoreCurrentTime }}
            - name: CRON_LOCAL_RUNNING_EXP 
              value: {{ .Values.cronLocalRunningExp | quote}}